---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    script: |
      #!/bin/bash
      echo -e "----------------------------------------------------------------------------------"

