version: '2'
template:
  name: "Toolchain Template to setup a Test App"
  description: "Toolchain template to setup Continuous Delivery and Test of an App"
  icon: toolchainIcon.png
  #image: toolchain.png
  info:
    git url: >-
      [https://github.com/TinaLindhqvist/minimal-toolchain](https://github.com/TinaLindhqvist/minimal-toolchain)
    git branch: >-
      [master](https://github.com/TinaLindhqvist/minimal-toolchain/tree/master)
toolchain:
  name: 'theTestAPP-{{timestamp}}'
  template:
    getting_started: "A Toolchain for a Test App with multiple useful integrations. Enjoy!"
services:
  #GitLab
  repo:
    service_id: hostedgit
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: 'https://github.com/TinaLindhqvist/theTestAPP'
      type: clone
      has_issues: true
      enable_traceability: true
  #Web IDE
  webide:
    service_id: orion
  #Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
 #         CF_APP_NAME: '{{form.pipeline.parameters.prod-app-name}}'
 #         PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
 #         PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
 #         PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
        execute: true
  #Slack
  slack:
    service_id: slack
  #SauceLabs
  saucelabs:
    service_id: saucelabs
  #Trello
  othertool-Trello:
    service_id: customtool
    parameters:
      name: 'Trello'
      description: 'Test App To Do'
      type: 'Trello'
      lifecyclePhase: 'THINK'
      #imageUrl: trello.png
      documentationUrl: 'https://tech.trello.com/'
      dashboard_url: 'https://trello.com/b/vYfDPh37/tcsetup'
  #Availability Monitoring
  apm:
    service_id: apm
#form:
#  pipeline:
#    parameters:
#      prod-app-name: '{{services.repo.parameters.repo_name}}'
#    schema:
#      $ref: deploy.json
